---
title: "datathon-weather"
format: pdf
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Weather Data

```{r}
toronto_weather_all_data <- read_csv("en_climate_daily_ON_6158355_2024_P1D.csv")
toronto_weather_all_data
```

```{r}
toronto_weather <- toronto_weather_all_data |>
  select(`Date/Time`, Year, Month, Day, `Max Temp (°C)`, `Min Temp (°C)`, `Total Precip (mm)`, `Snow on Grnd (cm)`) |>
  mutate("date" = `Date/Time`) |>
  select(-`Date/Time`)

toronto_weather
```

```{r}
#ttc data
subway_data <- read_csv("ttc_subway_delay.csv")
streetcar_data <- read_csv("ttc_streetcar_delay.csv")
bus_data <- read_csv("ttc_bus_delay.csv")
subway_data 
streetcar_data
bus_data
```

```{r}
#merging ttc data with weather data
subway_with_weather <- merge(subway_data, toronto_weather, by = "date")
subway_with_weather

streetcar_with_weather <- merge(streetcar_data, toronto_weather, by = "date")
streetcar_with_weather

bus_with_weather <- merge(bus_data, toronto_weather, by = "date")
bus_with_weather

#write.csv(subway_with_weather, "subway_with_weather.csv")
#write.csv(streetcar_with_weather, "streetcar_with_weather.csv")
#write.csv(bus_with_weather, "bus_with_weather.csv")
```

```{r}
# visualise weather and bus delays
precipitation_by_bus_delay <- bus_with_weather |>
  ggplot() +
  geom_point(aes(x = `Total Precip (mm)`, y = `min_delay`), alpha = 0.2) +
  labs(x = "Total Precipitation (mm)", y = "Bus Delay (minutes)")
precipitation_by_bus_delay

snow_by_bus_delay <- bus_with_weather |>
  ggplot() +
  geom_point(aes(x = `Snow on Grnd (cm)`, y = `min_delay`), alpha = 0.3) +
  labs(x = "Snow on Ground (cm)", y = "Bus Delay (minutes)")
snow_by_bus_delay

```

```{r}
precipitation_by_streetcar_delay <- streetcar_with_weather |>
  ggplot() +
  geom_point(aes(x = `Total Precip (mm)`, y = `min_delay`), alpha = 0.2) +
  labs(x = "Total Precipitation (mm)", y = "Streetcar Delay (minutes)")
precipitation_by_streetcar_delay


snow_by_streetcar_delay <- streetcar_with_weather |>
  ggplot() +
  geom_point(aes(x = `Snow on Grnd (cm)`, y = `min_delay`), alpha = 0.3) +
  labs(x = "Snow on Ground (cm)", y = " Streetcar Delay (minutes)")
snow_by_streetcar_delay
```
